/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MicroDeprecated;

import MicroProtocol.MicroExperiment;
import MicroProtocol.ProtocolManagerMulti;
import MicroProtocol.SingleImageProcessing;
import MicroProtocol.menus.MultipleFilesMenu;
import vteaexploration.MicroExplorer;
import MicroProtocol.listeners.AnalysisStartListener;
import MicroProtocol.listeners.DeleteBlockListener;
import MicroProtocol.listeners.MicroBlockSetupListener;
import MicroProtocol.listeners.RebuildPanelListener;
import MicroProtocol.listeners.RepaintTabListener;
import MicroProtocol.listeners.RequestImageListener;
import MicroProtocol.listeners.TransferProtocolStepsListener;
import MicroProtocol.setup.MicroBlockObjectSetup;
import MicroProtocol.blockstepGUI.ProcessStepBlockGUI;
import VTC.ImageSelectionListener;
import ij.CompositeImage;
import ij.IJ;
import ij.ImagePlus;
import ij.plugin.frame.ContrastAdjuster;
import ij.process.LUT;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JWindow;
import vteapreprocessing.MicroProtocolPreProcessing;

/**
 *
 * @author vinfrais
 */
public class SingleImageProcessing_old extends javax.swing.JPanel implements ImageSelectionListener, TransferProtocolStepsListener, RebuildPanelListener, DeleteBlockListener {
    public static final int PROCESSBLOCKS = 1;
    public static final int OBJECTBLOCKS = 2;
    public static final int EXPLOREBLOCKS = 3;
    public static final int BATCH = 4;
    
    
    
    public JList OpenImages;
    //public microWindowManager openerWindow = new microWindowManager(OpenImages);
    
    protected ImagePlus OriginalImage;
    protected ImagePlus ProcessedImage;
    protected ImagePlus ThumbnailImage;
    protected JPanel thumbnail;
    
    protected Color ImageBlockBackground = new java.awt.Color(135, 175, 215);
    
//batch support
    
    public MultipleFilesMenu mfm = new MultipleFilesMenu(false);
    //public MicroBatchManager batchWindow = new MicroBatchManager(OpenImages);
    protected boolean batch = false;
    
    protected JList batchImages;

//private microFolio[] microFolios = new microFolio[10];
    private int folioCount = 0;

//private ArrayList <ProtocolManagerAnalysisStartListener> listeners = new ArrayList <ProtocolManagerAnalysisStartListener>();
    protected ArrayList<ProcessStepBlockGUI> ProcessingStepsList = new ArrayList<ProcessStepBlockGUI>();
    protected ArrayList<ObjectStepBlockGUI> ObjectStepsList = new ArrayList<ObjectStepBlockGUI>();
    protected ArrayList<ExploreStepBlockGUI> ExploreStepsList = new ArrayList<ExploreStepBlockGUI>();

    public JWindow thumb = new JWindow();

    protected GridLayout PreProcessingLayout = new GridLayout(5, 1, 0, 0);
    protected GridLayout ObjectLayout = new GridLayout(5, 1, 0, 0);
    protected GridLayout ExploreLayout = new GridLayout(5, 1, 0, 0);

    protected ArrayList<String> Channels;

    private ArrayList<AnalysisStartListener> listeners = new ArrayList<AnalysisStartListener>();
    private ArrayList<RequestImageListener> RequestImageListeners = new ArrayList<RequestImageListener>();
    private ArrayList<RepaintTabListener> RepaintTabListeners = new ArrayList<RepaintTabListener>();
    //private MicroExperiment me = new MicroExperiment();
    
    private int tab;
    /**
     * Creates new form NewJPanel
     */
    public SingleImageProcessing_old()  {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SingleImageProcessing = new javax.swing.JPanel();
        Preprocessing_Header = new javax.swing.JPanel();
        OpenImage = new javax.swing.JButton();
        PreProcessingLabel = new javax.swing.JLabel();
        AddStep_Preprocessing = new javax.swing.JButton();
        DeleteAllSteps_PreProcessing = new javax.swing.JButton();
        PreProcessing_Panel = new javax.swing.JPanel();
        PreProcessingStepsPanel = new javax.swing.JPanel();
        PreProcessingGo = new javax.swing.JButton();
        Object_Header = new javax.swing.JPanel();
        ObjectsLabel = new javax.swing.JLabel();
        AddStep_Object = new javax.swing.JButton();
        DeleteAllSteps_Object = new javax.swing.JButton();
        Object_Panel = new javax.swing.JPanel();
        ObjectStepsPanel = new javax.swing.JPanel();
        ObjectGo = new javax.swing.JButton();
        ObjectProcess = new javax.swing.JProgressBar();
        Explore_Header = new javax.swing.JPanel();
        ExplorationLabel = new javax.swing.JLabel();
        AddStep_Explore = new javax.swing.JButton();
        DeleteAll_Explores = new javax.swing.JButton();
        Explore_Panel = new javax.swing.JPanel();
        ExploreStepsPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(690, 420));
        setMinimumSize(new java.awt.Dimension(690, 420));
        setPreferredSize(new java.awt.Dimension(690, 420));

        SingleImageProcessing.setLayout(new java.awt.GridBagLayout());

        Preprocessing_Header.setBackground(new java.awt.Color(204, 204, 204));
        Preprocessing_Header.setForeground(new java.awt.Color(102, 102, 102));
        Preprocessing_Header.setAlignmentX(0.0F);
        Preprocessing_Header.setAlignmentY(0.0F);
        Preprocessing_Header.setMaximumSize(new java.awt.Dimension(160, 36));
        Preprocessing_Header.setMinimumSize(new java.awt.Dimension(160, 36));
        Preprocessing_Header.setPreferredSize(new java.awt.Dimension(160, 36));
        Preprocessing_Header.setLayout(new java.awt.GridBagLayout());

        OpenImage.setBackground(VTC._VTC.BUTTONBACKGROUND);
        OpenImage.setForeground(new java.awt.Color(102, 102, 102));
        OpenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/insert-image-2 copy.png"))); // NOI18N
        OpenImage.setPreferredSize(new java.awt.Dimension(34, 34));
        OpenImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenImageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Preprocessing_Header.add(OpenImage, gridBagConstraints);

        PreProcessingLabel.setBackground(new java.awt.Color(204, 204, 204));
        PreProcessingLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        PreProcessingLabel.setText("Process ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        Preprocessing_Header.add(PreProcessingLabel, gridBagConstraints);

        AddStep_Preprocessing.setBackground(new java.awt.Color(102, 102, 102));
        AddStep_Preprocessing.setForeground(new java.awt.Color(102, 102, 102));
        AddStep_Preprocessing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list-add-3 2.png"))); // NOI18N
        AddStep_Preprocessing.setToolTipText("Adds a preprocessing step.");
        AddStep_Preprocessing.setEnabled(false);
        AddStep_Preprocessing.setMaximumSize(new java.awt.Dimension(32, 32));
        AddStep_Preprocessing.setMinimumSize(new java.awt.Dimension(32, 32));
        AddStep_Preprocessing.setName(""); // NOI18N
        AddStep_Preprocessing.setPreferredSize(new java.awt.Dimension(34, 34));
        AddStep_Preprocessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStep_PreprocessingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        Preprocessing_Header.add(AddStep_Preprocessing, gridBagConstraints);

        DeleteAllSteps_PreProcessing.setBackground(VTC._VTC.BUTTONBACKGROUND);
        DeleteAllSteps_PreProcessing.setForeground(new java.awt.Color(102, 102, 102));
        DeleteAllSteps_PreProcessing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-clear-list_24.png"))); // NOI18N
        DeleteAllSteps_PreProcessing.setPreferredSize(new java.awt.Dimension(34, 34));
        DeleteAllSteps_PreProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllSteps_PreProcessingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        Preprocessing_Header.add(DeleteAllSteps_PreProcessing, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        SingleImageProcessing.add(Preprocessing_Header, gridBagConstraints);

        PreProcessing_Panel.setBackground(new java.awt.Color(204, 204, 204));
        PreProcessing_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PreProcessing_Panel.setForeground(new java.awt.Color(102, 102, 102));
        PreProcessing_Panel.setAlignmentX(0.0F);
        PreProcessing_Panel.setAlignmentY(0.0F);
        PreProcessing_Panel.setMaximumSize(new java.awt.Dimension(220, 400));
        PreProcessing_Panel.setMinimumSize(new java.awt.Dimension(220, 400));
        PreProcessing_Panel.setPreferredSize(new java.awt.Dimension(220, 360));

        PreProcessingStepsPanel.setBackground(VTC._VTC.ACTIONPANELBACKGROUND);
        PreProcessingStepsPanel.setPreferredSize(new java.awt.Dimension(196, 306));

        javax.swing.GroupLayout PreProcessingStepsPanelLayout = new javax.swing.GroupLayout(PreProcessingStepsPanel);
        PreProcessingStepsPanel.setLayout(PreProcessingStepsPanelLayout);
        PreProcessingStepsPanelLayout.setHorizontalGroup(
            PreProcessingStepsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        PreProcessingStepsPanelLayout.setVerticalGroup(
            PreProcessingStepsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        PreProcessingGo.setBackground(VTC._VTC.BUTTONBACKGROUND);
        PreProcessingGo.setText("Process");
        PreProcessingGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreProcessingGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PreProcessing_PanelLayout = new javax.swing.GroupLayout(PreProcessing_Panel);
        PreProcessing_Panel.setLayout(PreProcessing_PanelLayout);
        PreProcessing_PanelLayout.setHorizontalGroup(
            PreProcessing_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PreProcessing_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PreProcessing_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PreProcessingStepsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreProcessingGo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PreProcessing_PanelLayout.setVerticalGroup(
            PreProcessing_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PreProcessing_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PreProcessingStepsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PreProcessingGo)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        SingleImageProcessing.add(PreProcessing_Panel, gridBagConstraints);

        Object_Header.setBackground(new java.awt.Color(204, 204, 204));
        Object_Header.setForeground(new java.awt.Color(102, 102, 102));
        Object_Header.setAlignmentX(0.0F);
        Object_Header.setAlignmentY(0.0F);
        Object_Header.setMaximumSize(new java.awt.Dimension(160, 36));
        Object_Header.setMinimumSize(new java.awt.Dimension(160, 36));
        Object_Header.setPreferredSize(new java.awt.Dimension(160, 36));
        Object_Header.setLayout(new java.awt.GridBagLayout());

        ObjectsLabel.setBackground(new java.awt.Color(0, 0, 0));
        ObjectsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        ObjectsLabel.setText(" Segment");
        ObjectsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ObjectsLabel.setMaximumSize(new java.awt.Dimension(150, 28));
        ObjectsLabel.setMinimumSize(new java.awt.Dimension(150, 28));
        ObjectsLabel.setPreferredSize(new java.awt.Dimension(150, 28));
        Object_Header.add(ObjectsLabel, new java.awt.GridBagConstraints());

        AddStep_Object.setBackground(new java.awt.Color(102, 102, 102));
        AddStep_Object.setForeground(new java.awt.Color(102, 102, 102));
        AddStep_Object.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list-add-3 2.png"))); // NOI18N
        AddStep_Object.setPreferredSize(new java.awt.Dimension(34, 34));
        AddStep_Object.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStep_ObjectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        Object_Header.add(AddStep_Object, gridBagConstraints);

        DeleteAllSteps_Object.setBackground(new java.awt.Color(102, 102, 102));
        DeleteAllSteps_Object.setForeground(new java.awt.Color(102, 102, 102));
        DeleteAllSteps_Object.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-clear-list_24.png"))); // NOI18N
        DeleteAllSteps_Object.setPreferredSize(new java.awt.Dimension(34, 34));
        DeleteAllSteps_Object.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllSteps_ObjectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        Object_Header.add(DeleteAllSteps_Object, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        SingleImageProcessing.add(Object_Header, gridBagConstraints);

        Object_Panel.setBackground(new java.awt.Color(204, 204, 204));
        Object_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Object_Panel.setForeground(new java.awt.Color(102, 102, 102));
        Object_Panel.setAlignmentX(0.0F);
        Object_Panel.setAlignmentY(0.0F);
        Object_Panel.setMaximumSize(new java.awt.Dimension(220, 400));
        Object_Panel.setMinimumSize(new java.awt.Dimension(220, 400));
        Object_Panel.setPreferredSize(new java.awt.Dimension(220, 360));
        Object_Panel.setRequestFocusEnabled(false);

        ObjectStepsPanel.setBackground(VTC._VTC.ACTIONPANELBACKGROUND);
        ObjectStepsPanel.setPreferredSize(new java.awt.Dimension(160, 305));

        javax.swing.GroupLayout ObjectStepsPanelLayout = new javax.swing.GroupLayout(ObjectStepsPanel);
        ObjectStepsPanel.setLayout(ObjectStepsPanelLayout);
        ObjectStepsPanelLayout.setHorizontalGroup(
            ObjectStepsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        ObjectStepsPanelLayout.setVerticalGroup(
            ObjectStepsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        ObjectGo.setBackground(VTC._VTC.BUTTONBACKGROUND);
        ObjectGo.setText("Find Objects");
        ObjectGo.setToolTipText("");
        ObjectGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObjectGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Object_PanelLayout = new javax.swing.GroupLayout(Object_Panel);
        Object_Panel.setLayout(Object_PanelLayout);
        Object_PanelLayout.setHorizontalGroup(
            Object_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Object_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Object_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Object_PanelLayout.createSequentialGroup()
                        .addComponent(ObjectStepsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Object_PanelLayout.createSequentialGroup()
                        .addComponent(ObjectGo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ObjectProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Object_PanelLayout.setVerticalGroup(
            Object_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Object_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ObjectStepsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Object_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ObjectGo)
                    .addComponent(ObjectProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        SingleImageProcessing.add(Object_Panel, gridBagConstraints);

        Explore_Header.setBackground(new java.awt.Color(204, 204, 204));
        Explore_Header.setForeground(new java.awt.Color(102, 102, 102));
        Explore_Header.setAlignmentX(0.0F);
        Explore_Header.setAlignmentY(0.0F);
        Explore_Header.setMaximumSize(new java.awt.Dimension(160, 36));
        Explore_Header.setMinimumSize(new java.awt.Dimension(160, 36));
        Explore_Header.setPreferredSize(new java.awt.Dimension(160, 36));
        Explore_Header.setLayout(new java.awt.GridBagLayout());

        ExplorationLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        ExplorationLabel.setText(" Explore    ");
        ExplorationLabel.setMaximumSize(new java.awt.Dimension(150, 29));
        ExplorationLabel.setMinimumSize(new java.awt.Dimension(120, 29));
        ExplorationLabel.setPreferredSize(new java.awt.Dimension(120, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        Explore_Header.add(ExplorationLabel, gridBagConstraints);

        AddStep_Explore.setBackground(new java.awt.Color(102, 102, 102));
        AddStep_Explore.setForeground(new java.awt.Color(102, 102, 102));
        AddStep_Explore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list-add-3 2.png"))); // NOI18N
        AddStep_Explore.setPreferredSize(new java.awt.Dimension(34, 34));
        AddStep_Explore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStep_ExploreActionPerformed(evt);
            }
        });
        Explore_Header.add(AddStep_Explore, new java.awt.GridBagConstraints());

        DeleteAll_Explores.setBackground(new java.awt.Color(102, 102, 102));
        DeleteAll_Explores.setForeground(new java.awt.Color(102, 102, 102));
        DeleteAll_Explores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-clear-list_24.png"))); // NOI18N
        DeleteAll_Explores.setPreferredSize(new java.awt.Dimension(34, 34));
        DeleteAll_Explores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAll_ExploresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Explore_Header.add(DeleteAll_Explores, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        SingleImageProcessing.add(Explore_Header, gridBagConstraints);

        Explore_Panel.setBackground(new java.awt.Color(204, 204, 204));
        Explore_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Explore_Panel.setForeground(new java.awt.Color(102, 102, 102));
        Explore_Panel.setAlignmentX(0.0F);
        Explore_Panel.setAlignmentY(0.0F);
        Explore_Panel.setAutoscrolls(true);
        Explore_Panel.setMaximumSize(new java.awt.Dimension(220, 400));
        Explore_Panel.setMinimumSize(new java.awt.Dimension(220, 400));
        Explore_Panel.setPreferredSize(new java.awt.Dimension(220, 360));

        ExploreStepsPanel.setBackground(VTC._VTC.ACTIONPANELBACKGROUND);
        ExploreStepsPanel.setPreferredSize(new java.awt.Dimension(160, 305));

        javax.swing.GroupLayout ExploreStepsPanelLayout = new javax.swing.GroupLayout(ExploreStepsPanel);
        ExploreStepsPanel.setLayout(ExploreStepsPanelLayout);
        ExploreStepsPanelLayout.setHorizontalGroup(
            ExploreStepsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        ExploreStepsPanelLayout.setVerticalGroup(
            ExploreStepsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Explore_PanelLayout = new javax.swing.GroupLayout(Explore_Panel);
        Explore_Panel.setLayout(Explore_PanelLayout);
        Explore_PanelLayout.setHorizontalGroup(
            Explore_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Explore_PanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ExploreStepsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Explore_PanelLayout.setVerticalGroup(
            Explore_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Explore_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExploreStepsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        SingleImageProcessing.add(Explore_Panel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SingleImageProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SingleImageProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OpenImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenImageActionPerformed
        // TODO add your handling code here:
        this.notifyRequestImageListeners(tab);
        this.notifyRepaintTabListeners();
        //openerWindow.updateImages();
        //openerWindow.getImageFile(tab);
    }//GEN-LAST:event_OpenImageActionPerformed

    private void AddStep_PreprocessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStep_PreprocessingActionPerformed
        // TODO add your handling code here:
        if (ProcessingStepsList.size() > 0) {
            
            ProcessStepBlockGUI block = new ProcessStepBlockGUI("Process Step", "", Color.LIGHT_GRAY, false, ThumbnailImage, OriginalImage, Channels, ProtocolManagerMulti.PROCESS, ProcessingStepsList.size()+1);
            block.addDeleteBlockListener(this);
            block.addRebuildPanelListener(this);
            this.notifyRepaintTabListeners();
            PreProcessingStepsPanel.setLayout(PreProcessingLayout);
            PreProcessingStepsPanel.add(block.getPanel());
            PreProcessingStepsPanel.repaint();
            //pack();

            ProcessingStepsList.add(block);

            if (ProcessingStepsList.size() <= 4) {

                AddStep_Preprocessing.setEnabled(true);
            }
            if (ProcessingStepsList.size() >= 5) {

                AddStep_Preprocessing.setEnabled(false);
            }
        }
        this.notifyRepaintTabListeners();
    }//GEN-LAST:event_AddStep_PreprocessingActionPerformed

    private void DeleteAllSteps_PreProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllSteps_PreProcessingActionPerformed
        // TODO add your handling code here:

        ProcessingStepsList.clear();
        PreProcessingStepsPanel.removeAll();
        AddStep_Preprocessing.setEnabled(false);
        PreProcessingStepsPanel.repaint();
        //pack();
    }//GEN-LAST:event_DeleteAllSteps_PreProcessingActionPerformed

    private void PreProcessingGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreProcessingGoActionPerformed
        executeProcessing();
    }//GEN-LAST:event_PreProcessingGoActionPerformed

    private void AddStep_ObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStep_ObjectActionPerformed
        // TODO add your handling code here:
        //if(ObjectStepsList.size() > 0){
            ObjectStepBlockGUI block = new ObjectStepBlockGUI();

            ObjectStepsPanel.setLayout(ObjectLayout);
            ObjectStepsPanel.add(block.getPanel());
            ObjectStepsPanel.repaint();
            //pack();

            ObjectStepsList.add(block);

            if (ObjectStepsList.size() <= 4) {

                AddStep_Object.setEnabled(true);
            }
            if (ObjectStepsList.size() >= 5) {

                AddStep_Object.setEnabled(false);
            }
          
           this.notifyRepaintTabListeners();
    }//GEN-LAST:event_AddStep_ObjectActionPerformed

    private void DeleteAllSteps_ObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllSteps_ObjectActionPerformed
        ObjectStepsList.clear();
        ObjectStepsPanel.removeAll();
        AddStep_Object.setEnabled(true);
        ObjectStepsPanel.repaint();
        //pack();
    }//GEN-LAST:event_DeleteAllSteps_ObjectActionPerformed

    private void ObjectGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObjectGoActionPerformed
        // TODO add your handling code here:
        executeObjectFinding();
    }//GEN-LAST:event_ObjectGoActionPerformed

    private void AddStep_ExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStep_ExploreActionPerformed
        ExploreStepBlockGUI block = new ExploreStepBlockGUI();

        ExploreStepsPanel.setLayout(ExploreLayout);
        ExploreStepsPanel.add(block.getPanel());
        ExploreStepsPanel.repaint();
        //pack();

        ExploreStepsList.add(block);

        if (ExploreStepsList.size() <= 4) {

            AddStep_Explore.setEnabled(true);
        }
        if (ExploreStepsList.size() >= 5) {

            AddStep_Explore.setEnabled(false);
        }
    }//GEN-LAST:event_AddStep_ExploreActionPerformed

    private void DeleteAll_ExploresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAll_ExploresActionPerformed
        ExploreStepsList.clear();
        ExploreStepsPanel.removeAll();
        AddStep_Explore.setEnabled(true);
        ExploreStepsPanel.repaint();
        //pack();
    }//GEN-LAST:event_DeleteAll_ExploresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStep_Explore;
    private javax.swing.JButton AddStep_Object;
    public javax.swing.JButton AddStep_Preprocessing;
    private javax.swing.JButton DeleteAllSteps_Object;
    private javax.swing.JButton DeleteAllSteps_PreProcessing;
    private javax.swing.JButton DeleteAll_Explores;
    private javax.swing.JLabel ExplorationLabel;
    public javax.swing.JPanel ExploreStepsPanel;
    private javax.swing.JPanel Explore_Header;
    private javax.swing.JPanel Explore_Panel;
    private javax.swing.JButton ObjectGo;
    private javax.swing.JProgressBar ObjectProcess;
    public javax.swing.JPanel ObjectStepsPanel;
    private javax.swing.JPanel Object_Header;
    private javax.swing.JPanel Object_Panel;
    private javax.swing.JLabel ObjectsLabel;
    private javax.swing.JButton OpenImage;
    private javax.swing.JButton PreProcessingGo;
    private javax.swing.JLabel PreProcessingLabel;
    public javax.swing.JPanel PreProcessingStepsPanel;
    public javax.swing.JPanel PreProcessing_Panel;
    private javax.swing.JPanel Preprocessing_Header;
    private javax.swing.JPanel SingleImageProcessing;
    // End of variables declaration//GEN-END:variables


  
    //classes for batch processing

    public void setTabValue(int tab){this.tab = tab;}
    
    public void processBatchFileList(){}
   
    public void findObjectsBatchFileList(){}
    
    //public void 

    @Override
    public void transferThese(int type, int tab, String arg) {
        if(this.tab == tab){
    }
    }

    @Override
    public void rebuildPanel(int type) {   
        switch(type){
            case ProtocolManagerMulti.PROCESS: this.RebuildPanelProcessing(); return;
           
            case ProtocolManagerMulti.EXPLORATION: this.RebuildPanelExplore(); return;
                    
            case ProtocolManagerMulti.OBJECT: this.RebuildPanelObject(); return;
  
            default: return;
        }
    }

    @Override
    public void deleteBlock(int type, int position) {
        switch(type){
            case ProtocolManagerMulti.PROCESS: IJ.log("Size of Block list before deletion: " + this.ProcessingStepsList.size()); this.deleteProcessStep(position); IJ.log("Size of Block list after deletion: " + this.ProcessingStepsList.size());return;
           
            case ProtocolManagerMulti.EXPLORATION: this.deleteExploreStep(position); return;
                    
            case ProtocolManagerMulti.OBJECT: this.deleteObjectStep(position); return;
  
            default: return;
        }
    }

    
//classes for step blocks
    private final class ObjectStepBlockGUI extends Object implements MicroBlockSetupListener {

        JPanel step = new JPanel();
        Font PositionFont = new Font("Arial", Font.PLAIN, 16);
        Font ObjectFont = new Font("Arial", Font.BOLD, 12);
        Font CommentFont = new Font("Arial", Font.ITALIC, 10);
        JLabel Position = new JLabel();
        JLabel Comment = new JLabel("Block by Block");
        JLabel Object = new JLabel("First things first");
        boolean ProcessTypeSet = false;
        int position;

        MicroBlockObjectSetup mbs;

        private ArrayList settings;

        public ObjectStepBlockGUI() {
            BuildStepBlock("Empty Step", "", Color.LIGHT_GRAY);
        }

        public ObjectStepBlockGUI(String ProcessText, String CommentText, Color BlockColor) {
            BuildStepBlock(ProcessText, CommentText, Color.GREEN);
        }

        private void BuildStepBlock(String ProcessText, String CommentText, Color BlockColor) {

            if (ObjectStepsList.isEmpty()) {
                position = 1;
            } else {
                position = ObjectStepsList.size() + 1;
            }

            Object.setText(ProcessText);

            Comment.setText(CommentText);
            step.setBackground(BlockColor);

            //need max size set here
            Position.setText("Classifier#" + position);
            Position.setFont(PositionFont);

            if (Object.getText().length() > 12) {
                ObjectFont = new Font("Arial", Font.BOLD, 8);
            }
            if (Comment.getText().length() > 12) {
                CommentFont = new Font("Arial", Font.BOLD, 5);
            }

            Object.setFont(ObjectFont);
            Comment.setFont(CommentFont);

            mbs = new MicroBlockObjectSetup(position, Channels);

            mbs.setVisible(false);
            mbs.addMicroBlockSetupListener(this);

            JButton DeleteButton = new JButton();
            DeleteButton.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    deleteObjectStep(position);
                }
            });

            JButton EditButton = new JButton();
            EditButton.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    mbs.setVisible(true);
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            });

            DeleteButton.setSize(20, 20);
            DeleteButton.setBackground(VTC._VTC.BUTTONBACKGROUND);
            DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-delete-6_16.png")));

            EditButton.setSize(20, 20);
            EditButton.setBackground(VTC._VTC.BUTTONBACKGROUND);
            EditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-4.png")));

            step.setSize(205, 20);
            step.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            step.setLayout(new GridBagLayout());
            GridBagConstraints layoutConstraints = new GridBagConstraints();

            layoutConstraints.fill = GridBagConstraints.HORIZONTAL;
            layoutConstraints.gridx = 0;
            layoutConstraints.gridy = 0;
            layoutConstraints.weightx = 1;
            layoutConstraints.weighty = 1;
            step.add(Position, layoutConstraints);

            layoutConstraints.fill = GridBagConstraints.HORIZONTAL;
            layoutConstraints.gridx = 1;
            layoutConstraints.gridy = 0;
            layoutConstraints.weightx = 20;
            layoutConstraints.weighty = 20;
            step.add(Object, layoutConstraints);

            layoutConstraints.fill = GridBagConstraints.HORIZONTAL;
            layoutConstraints.gridx = 1;
            layoutConstraints.gridy = 1;
            layoutConstraints.weightx = 20;
            layoutConstraints.weighty = 20;
            step.add(Comment, layoutConstraints);

            layoutConstraints.fill = GridBagConstraints.BOTH;
            layoutConstraints.gridx = 2;
            layoutConstraints.gridy = 0;
            layoutConstraints.weightx = -1;
            layoutConstraints.weighty = -1;
            layoutConstraints.ipadx = -1;
            layoutConstraints.ipady = -1;
            step.add(DeleteButton, layoutConstraints);

            layoutConstraints.fill = GridBagConstraints.BOTH;
            layoutConstraints.gridx = 2;
            layoutConstraints.gridy = 1;
            layoutConstraints.weightx = -1;
            layoutConstraints.weighty = -1;
            layoutConstraints.ipadx = -1;
            layoutConstraints.ipady = -1;
            step.add(EditButton, layoutConstraints);

            step.addMouseListener(new java.awt.event.MouseListener() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                }

                ;
            @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    //thumb.setVisible(false);
                }

                ;
            @Override
                public void mouseReleased(java.awt.event.MouseEvent evt) {
                    thumb.setVisible(false);
                }

                ;
            @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
//                    thumb.setSize(150, 150);
//                    thumb.setLocation(evt.getX(), evt.getY());
//                    thumb.setVisible(true);
                }

                ;
            @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                }
            ;
        }

        );
        }

        public void setPosition(int n) {
            position = n;
            Position.setText(position + ".");
        }

        public JPanel getPanel() {
            return step;
        }

        public int getPosition() {
            return position;
        }

        public ArrayList getVariables() {
            return settings;
        }

        @Override
        public void onChangeSetup(ArrayList al2) {

            ArrayList al = new ArrayList();

            al = (ArrayList) al2.get(0);

            Object.setText(VTC._VTC.PROCESSOPTIONS[0]);
            //Comment.setText(al.get(1).toString());
            RebuildPanelObject();
            this.settings = al2;

        }
    }

    private final class ExploreStepBlockGUI extends Object implements MicroBlockSetupListener {

        JPanel step = new JPanel();

        List protocoldetails = new ArrayList();
        final JComboBox objects = new JComboBox();

        Font PositionFont = new Font("Arial", Font.PLAIN, 18);
        Font ProcessFont = new Font("Arial", Font.BOLD, 12);
        Font CommentFont = new Font("Arial", Font.ITALIC, 10);
        JLabel Position = new JLabel();
        JLabel Comment = new JLabel("");
        JLabel Process = new JLabel("");
        boolean ProcessTypeSet = false;
        int position;

        MicroExplorer me;

        public ExploreStepBlockGUI() {
            BuildStepBlock("Some process", "this is a critical step", Color.LIGHT_GRAY);
        }

        public ExploreStepBlockGUI(String ProcessText, String CommentText, Color BlockColor) {
            BuildStepBlock(ProcessText, CommentText, BlockColor);
        }

        ;

        private void BuildStepBlock(String ProcessText, String CommentText, Color BlockColor) {

            protocoldetails = ExtractSteps(ObjectStepsList, OBJECTBLOCKS);

            final JComboBox objects = new JComboBox();
            List placeholder = new ArrayList();

            //for (int i = 0; i <= protocoldetails.size() - 1; i++) {
            placeholder = (ArrayList) (protocoldetails.get(0));
            objects.addItem("CH." + placeholder.get(0));

            //     + " " + MicroBlockObjectSetup.getMethod(Integer.parseInt(placeholder.get(1).toString())));
            //}
            if (ExploreStepsList.isEmpty()) {
                position = 1;
            } else {
                position = ExploreStepsList.size() + 1;
            }

            Process.setText(ProcessText);

            Comment.setText(CommentText);
            step.setBackground(BlockColor);

            //need max size set here
            Position.setText(position + ".");

            Position.setFont(PositionFont);

            if (Process.getText().length() > 12) {
                ProcessFont = new Font("Arial", Font.BOLD, 8);
            }
            if (Comment.getText().length() > 12) {
                CommentFont = new Font("Arial", Font.BOLD, 5);
            }

            Process.setFont(ProcessFont);
            Comment.setFont(CommentFont);

            JButton DeleteButton = new JButton();
            DeleteButton.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {

                    deleteExploreStep(position);

                    // throw new UnsupportedOperationException("Block Delete Requested."); //To change body of generated methods, choose Tools | Templates.
                }
            });

            JButton ViewButton = new JButton();
            ViewButton.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    IJ.log("Requesting explorer window for object: " + (Integer)objects.getSelectedIndex());
                    executeExploring((Integer)objects.getSelectedIndex());
                    IJ.log("Explorer window openned!");
                }
            });

            DeleteButton.setSize(20, 20);
            DeleteButton.setBackground(VTC._VTC.BUTTONBACKGROUND);
            DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-delete-6_16.png")));

            ViewButton.setSize(20, 20);
            ViewButton.setBackground(VTC._VTC.BUTTONBACKGROUND);
            ViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-4.png")));

            step.setSize(205, 20);
            step.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            step.setLayout(new GridBagLayout());
            GridBagConstraints layoutConstraints = new GridBagConstraints();

            layoutConstraints.fill = GridBagConstraints.HORIZONTAL;
            layoutConstraints.gridx = 0;
            layoutConstraints.gridy = 0;
            layoutConstraints.weightx = 1;
            layoutConstraints.weighty = 1;
            step.add(Position, layoutConstraints);

            layoutConstraints.fill = GridBagConstraints.HORIZONTAL;
            layoutConstraints.gridx = 1;
            layoutConstraints.gridy = 0;
            layoutConstraints.weightx = 20;
            layoutConstraints.weighty = 20;
            step.add(objects, layoutConstraints);

            layoutConstraints.fill = GridBagConstraints.HORIZONTAL;
            layoutConstraints.gridx = 1;
            layoutConstraints.gridy = 1;
            layoutConstraints.weightx = 20;
            layoutConstraints.weighty = 20;
            step.add(Comment, layoutConstraints);

            layoutConstraints.fill = GridBagConstraints.BOTH;
            layoutConstraints.gridx = 2;
            layoutConstraints.gridy = 0;
            layoutConstraints.weightx = -1;
            layoutConstraints.weighty = -1;
            layoutConstraints.ipadx = -1;
            layoutConstraints.ipady = -1;
            step.add(DeleteButton, layoutConstraints);
            layoutConstraints.fill = GridBagConstraints.BOTH;
            layoutConstraints.gridx = 2;
            layoutConstraints.gridy = 1;
            layoutConstraints.weightx = -1;
            layoutConstraints.weighty = -1;
            layoutConstraints.ipadx = -1;
            layoutConstraints.ipady = -1;
            step.add(ViewButton, layoutConstraints);

            step.addMouseListener(new java.awt.event.MouseListener() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                }

                ;
            @Override
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    //thumb.setVisible(false);
                }

                ;
            @Override
                public void mouseReleased(java.awt.event.MouseEvent evt) {
                }

                ;
            @Override
                public void mousePressed(java.awt.event.MouseEvent evt) {
                }

                ;
            @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                }
            ;
        }

        );
       }

        public void setPosition(int n) {
            position = n;
            Position.setText(position + ".");
        }

        public JPanel getPanel() {
            return step;
        }

        public int getPosition() {
            return position;
        }

        @Override
        public void onChangeSetup(ArrayList al) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

    }

    
    //GUI table manipulation
    
    private void deleteProcessStep(int position) {

        //remove from PreProcessingStepsList
        
        
        
        ProcessingStepsList.remove(position - 1);

        //IJ.showMessage("Block "+position+" removed from list");
        //refactor postions of objects in List
        UpdatePositionProcessing(position - 1);

        //IJ.showMessage("Refactored position, " + PreProcessingStepsList.size()+ " blocks remain.");
        ProcessingStepsList.trimToSize();

        //IJ.showMessage("List trimmed to size");
        //reset PreProcessingStepsPanel
        PreProcessingStepsPanel.removeAll();
        //PreProcessingStepsPanel.setSize(WIDTH, WIDTH);
        PreProcessingStepsPanel.setLayout(PreProcessingLayout);

        //IJ.showMessage("Panel cleared position");
        //rebuild Panel,  will need to generalize this for use with object finding
        if (ProcessingStepsList.size() < 0) {
        } else {
            RebuildPanelProcessing();
        }

        //IJ.showMessage("Panel rebuilt");
        if (ProcessingStepsList.size() < 5) {
            AddStep_Preprocessing.setEnabled(true);
        }

        PreProcessingStepsPanel.repaint();
        this.notifyRepaintTabListeners();
        //pack();

    }

    private void deleteObjectStep(int position) {

        //remove from ObjectList
        ObjectStepsList.remove(position - 1);

        //IJ.showMessage("Block "+position+" removed from list");
        //refactor postions of objects in List
        UpdatePositionObject(position);

        //IJ.showMessage("Refactored position, " + PreProcessingStepsList.size()+ " blocks remain.");
        ObjectStepsList.trimToSize();

        //IJ.showMessage("List trimmed to size");
        //reset PreProcessingStepsPanel
        ObjectStepsPanel.removeAll();

        ObjectStepsPanel.setLayout(ObjectLayout);

        //IJ.showMessage("Panel cleared position");
        //rebuild Panel
        if (ObjectStepsList.size() < 0) {
        } else {
            RebuildPanelObject();
        }

        //IJ.showMessage("Panel rebuilt");
        if (5 >= ObjectStepsList.size()) {
            AddStep_Object.setEnabled(true);
        }

        ObjectStepsPanel.repaint();
        this.notifyRepaintTabListeners();
        //pack();

    }

    private void deleteExploreStep(int position) {

        //remove from ObjectList
        ExploreStepsList.remove(position - 1);
        
        //refactor postions of objects in List
        UpdatePositionExplore(position);

        ExploreStepsList.trimToSize();

        ExploreStepsPanel.removeAll();

        ExploreStepsPanel.setLayout(ExploreLayout);

        //rebuild Panel
        if (ExploreStepsList.size() < 0) {
        } else {
            RebuildPanelExplore();
        }

        if (5 >= ExploreStepsList.size()) {
            AddStep_Explore.setEnabled(true);
        }

        ExploreStepsPanel.repaint();
        notifyRepaintTabListeners();
    }
    
    public ArrayList getProcessSteps(){
        
        ArrayList<ProcessStepBlockGUI> export = new ArrayList<ProcessStepBlockGUI>();
        
        for(ProcessStepBlockGUI block : ProcessingStepsList){
            try {
                export.add((ProcessStepBlockGUI)block.clone());
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(SingleImageProcessing.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        export.remove(0);
        return export;}
    
    public ArrayList getObjectSteps(){return this.ObjectStepsList;}
    
    public ArrayList getExploreSteps(){return this.ExploreStepsList;}
    
    
       public ArrayList getProProcessingProtocol(){
        return ExtractSteps(ProcessingStepsList, PROCESSBLOCKS);
        
    }
    
    public void setProcessSteps(ArrayList ProcessingStepsList){
        ProcessingStepsList.trimToSize();
        this.ProcessingStepsList.addAll(ProcessingStepsList); 
        //this.ProcessingStepsList.trimToSize(); 
        UpdatePositionProcessing(0);
        this.RebuildPanelProcessing();}
    
    public void setObjectSteps(ArrayList ObjectStepList){this.ObjectStepsList = ObjectStepList; this.RebuildPanelObject();}
    
    public void setExploreSteps(ArrayList ExploreStepList){this.ExploreStepsList = ExploreStepList; this.RebuildPanelExplore();}

    public void RebuildPanelProcessing() {

        ProcessStepBlockGUI sb;

        ListIterator litr = ProcessingStepsList.listIterator();
        while (litr.hasNext()) {
            sb = (ProcessStepBlockGUI) litr.next();
            sb.setPosition(ProcessingStepsList.indexOf(sb) + 1);
            PreProcessingStepsPanel.add(sb.getPanel());
        }

    }

    public void RebuildPanelObject() {

        ObjectStepBlockGUI sb;

        ListIterator litr = ObjectStepsList.listIterator();
        while (litr.hasNext()) {
            sb = (ObjectStepBlockGUI) litr.next();
            sb.setPosition(ObjectStepsList.indexOf(sb) + 1);

            ObjectStepsPanel.add(sb.getPanel());
        }

    }

    public void RebuildPanelExplore() {

        ExploreStepBlockGUI sb;

        ListIterator litr = ExploreStepsList.listIterator();
        while (litr.hasNext()) {
            sb = (ExploreStepBlockGUI) litr.next();
            sb.setPosition(ExploreStepsList.indexOf(sb) + 1);

            ExploreStepsPanel.add(sb.getPanel());
        }

    }

    public void UpdatePositionProcessing(int position) {

        ProcessStepBlockGUI sb;

        //ArrayList al = new ArrayList();
        if (ProcessingStepsList.size() > position + 1) {
            for (int i = position; i <= ProcessingStepsList.size()-position-1; i++) {

                sb = (ProcessStepBlockGUI) ProcessingStepsList.get(i);
                sb.setPosition(i-1);
                //PreProcessingStepsList.set(i-1, sb);

            }
        }
//        if(PreProcessingStepsList.isEmpty()) {position = 1;}
//        else{position = PreProcessingStepsList.size()+1;}

    }

    public void UpdatePositionObject(int position) {

        ObjectStepBlockGUI sb;

        //ArrayList al = new ArrayList();
        if (ObjectStepsList.size() > position + 1) {
            for (int i = position - 1; i <= ObjectStepsList.size() - 1; i++) {

                sb = (ObjectStepBlockGUI) ObjectStepsList.get(i);
                sb.setPosition(i - 1);
                ObjectStepsList.set(i, sb);

            }
        }
//        if(PreProcessingStepsList.isEmpty()) {position = 1;}
//        else{position = PreProcessingStepsList.size()+1;}

    }

    public void UpdatePositionExplore(int position) {

        ExploreStepBlockGUI esb;

        //ArrayList al = new ArrayList();
        if (ObjectStepsList.size() > position + 1) {
            for (int i = position - 1; i <= ExploreStepsList.size() - 1; i++) {

                esb = (ExploreStepBlockGUI) ExploreStepsList.get(i);
                esb.setPosition(i - 1);
                ExploreStepsList.set(i, esb);

            }
        }
//        if(PreProcessingStepsList.isEmpty()) {position = 1;}
//        else{position = PreProcessingStepsList.size()+1;}

    }

    public void UpdateImageList() {
        //openerWindow.updateImages();
    }
    
 

    
private void executeProcessing() {

        ArrayList protocol = new ArrayList();

//get the arraylist, decide the nubmer of steps, by .steps to do and whether this is a preview or final by .type
        protocol = ExtractSteps(ProcessingStepsList, PROCESSBLOCKS);

        MicroProtocolPreProcessing mpp = new MicroProtocolPreProcessing(OriginalImage, protocol);

        mpp.ProcessImage();

        this.ProcessedImage = mpp.getResult();
        this.ProcessedImage.setTitle(OriginalImage.getTitle()+"_Processed");
        this.ProcessedImage.show();
        
        
       

        //use function selection with a new class
        //new class for preprocessing?
//MicroPreProcessing mpp = new MicroPreProcessing(this.OriginalImage.duplicate(), protocol);
//
//this.ProcessedImage = mpp.ProcessImage();
//this.ProcessedImage.show();
//
    }

    ;

private void executeObjectFinding() {

        this.ObjectProcess.setIndeterminate(true);

        ArrayList protocol = new ArrayList();

        protocol = ExtractSteps(ObjectStepsList, OBJECTBLOCKS);

        IJ.log("ExtractStep result: " + protocol);
        //me.addFolder(ProcessedImage, protocol);
        this.ObjectProcess.setIndeterminate(false);

    }

    ;

private void executeExploring(int i) {
        //me.addExplore(ProcessedImage, "VTEA-Explorer Window, " + ProcessedImage.getTitle(), me.getVolumes(i), me.getAvailableData(i));
    }

    ;

private ArrayList ExtractSteps(ArrayList sb_al, int blocktype) {

        ArrayList Result = new ArrayList();

        if (blocktype == PROCESSBLOCKS) {

            ProcessStepBlockGUI ppsb;

            ListIterator<Object> litr = sb_al.listIterator();
            while (litr.hasNext()) {
                ppsb = (ProcessStepBlockGUI) litr.next();
                if (!(ppsb.Comment.getText()).equals("New Image")) {
                    Result.add(ppsb.getVariables());
                }
            }
        }

        if (blocktype == OBJECTBLOCKS) {

            ObjectStepBlockGUI osb;

            ListIterator<Object> litr = sb_al.listIterator();
            while (litr.hasNext()) {
                osb = (ObjectStepBlockGUI) litr.next();

                Result.add(osb.getVariables());
                System.out.println("OSB variables: " + Result);
            }
        }

        return Result;
    }

    public ImagePlus makeThumbnail(ImagePlus imp){    
        int nchannels = imp.getNChannels(); 
  
        
        CompositeImage compImp = new CompositeImage(imp, IJ.COMPOSITE);
        
        
        compImp.setPosition(imp.getStackSize()/2);
        compImp.setOpenAsHyperStack(true);
        
        
        for(int i = 1; i <= compImp.getNChannels(); i++){
            
            
            //compImp.setChannelLut(null, nchannels);
        
            
            switch(i){
                case 1:
                        compImp.setChannelLut(LUT.createLutFromColor(Color.CYAN),i);compImp.resetDisplayRange();break; 
                case 2:
                        compImp.setChannelLut(LUT.createLutFromColor(Color.RED),i);compImp.resetDisplayRange();break;
                case 3:
                        compImp.setChannelLut(LUT.createLutFromColor(Color.GREEN),i);compImp.resetDisplayRange();break;
                case 4:
                        compImp.setChannelLut(LUT.createLutFromColor(Color.MAGENTA),i);compImp.resetDisplayRange();break;        
                case 5:
                        compImp.setChannelLut(LUT.createLutFromColor(Color.YELLOW),i);compImp.resetDisplayRange();break;
                case 6:
                        compImp.setChannelLut(LUT.createLutFromColor(Color.BLUE),i);compImp.resetDisplayRange();break;
                case 7:
                        compImp.setChannelLut(LUT.createLutFromColor(Color.WHITE),i);compImp.resetDisplayRange();break;
                default:
                        break;
            }
            
          ContrastAdjuster.update();
          
        }
        compImp.flatten();
        return compImp;
    }
    
    public void setImage(ImagePlus imp, int tab){
        IJ.log("This tab: " + this.tab + " image for tab: " + tab);
      if((tab+1) == this.tab && (ProcessingStepsList.size() == 0)){ 
          
        this.OriginalImage = imp.duplicate();
         OriginalImage.setOpenAsHyperStack(true);
        
        this.ThumbnailImage = makeThumbnail(imp.duplicate());

        Channels = new ArrayList<String>();
        for (int i = 0; i <= OriginalImage.getNChannels() - 1; i++) {
            Channels.add("Channel_" + i);
        }

        AddStep_Preprocessing.setEnabled(true);

        ProcessStepBlockGUI block = new ProcessStepBlockGUI(imp.getTitle(), "New Image", Color.GREEN, this.batch, this.ThumbnailImage, this.OriginalImage ,this.Channels, ProtocolManagerMulti.PROCESS, getBlockPosition());
        
        //String ProcessText, String CommentText, Color BlockColor, boolean multiple, ImagePlus ThumbnailImage, String[] Channels, int type, int position
        PreProcessingStepsPanel.setLayout(PreProcessingLayout);
        PreProcessingStepsPanel.add(block.getPanel());
        PreProcessingStepsPanel.repaint();
        //pack();

        ProcessingStepsList.add(block);

        if (ProcessingStepsList.size() <= 4) {

            AddStep_Preprocessing.setEnabled(true);
        }
        if (ProcessingStepsList.size() >= 5) {

            AddStep_Preprocessing.setEnabled(false);
        }
    }
    }
    
    private int getBlockPosition(){
        int position;
                if (ProcessingStepsList.isEmpty()) {
                position = 1;
            } else {
                position = ProcessingStepsList.size() + 1;
            }
                return position;
    }
    
    

    public void addListener(AnalysisStartListener listener) {
        listeners.add(listener);
    }

    private void notifyListeners(int i) {
        for (AnalysisStartListener listener : listeners) {
            listener.onStartButton(i);
        }
    }
    
    public void addRequestImageListener(RequestImageListener listener) {
        RequestImageListeners.add(listener);
    }

    private void notifyRequestImageListeners(int tab) {
        for (RequestImageListener listener : RequestImageListeners) {
            listener.onRequest(tab);
        }
    }
    
    public void addRepaintTabListener(RepaintTabListener listener) {
        RepaintTabListeners.add(listener);
    }

    private void notifyRepaintTabListeners() {
        for (RepaintTabListener listener : RepaintTabListeners) {
            listener.repaintTab();
        }
    }

    @Override
    public void onSelect(ImagePlus imp, int tab) {
       // IJ.log("This tab: " + this.tab + " image for tab: " + tab);
      if(tab == this.tab && ProcessingStepsList.size() == 0){    
        this.OriginalImage = imp.duplicate();
         OriginalImage.setOpenAsHyperStack(true);
        
        this.ThumbnailImage = makeThumbnail(imp.duplicate());

        Channels = new ArrayList<String>();
        for (int i = 0; i <= OriginalImage.getNChannels() - 1; i++) {
            Channels.add("Channel_" + (i + 1));
        }

        AddStep_Preprocessing.setEnabled(true);

        ProcessStepBlockGUI block = new ProcessStepBlockGUI(imp.getTitle(), "New Image", ImageBlockBackground, this.batch, this.ThumbnailImage, this.OriginalImage,this.Channels, ProtocolManagerMulti.PROCESS, getBlockPosition());
        block.addRebuildPanelListener(this);
        PreProcessingStepsPanel.setLayout(PreProcessingLayout);
        PreProcessingStepsPanel.add(block.getPanel());
        PreProcessingStepsPanel.repaint();
        //pack();

        ProcessingStepsList.add(block);

        if (ProcessingStepsList.size() <= 4) {

            AddStep_Preprocessing.setEnabled(true);
        }
        if (ProcessingStepsList.size() >= 5) {

            AddStep_Preprocessing.setEnabled(false);
        }
    }
      this.notifyRepaintTabListeners();
    }
    
};
